# Generated by Django 3.2.18 on 2023-04-04 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('unit_number', models.PositiveIntegerField()),
                ('city', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('ST', 'Studio'), ('PR', 'Private Room'), ('LF', 'Loft'), ('HR', 'High Rise'), ('DL', 'Duplex')], default='PR', max_length=255)),
                ('price', models.PositiveIntegerField()),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='post_images')),
            ],
        ),
    ]
