# Generated by Django 4.2 on 2023-09-01 16:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hra_app', '0006_property_lister_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='lister_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
